[project]
name = "blackpythondevs-site"
version = "0.1.0"
description = "Black Python Devs community website"
requires-python = ">=3.13"
dependencies = [
    "render-engine[cli]>=2026.3.4a3",
    "pyyaml",
    "folium>=0.20.0",
]

[dependency-groups]
dev = [
  "pre-commit",
  "typer",
  "rich",
  "python-frontmatter",
  "pytest",
  "ruff",
]

[tool.render-engine.cli]
module = "app"
site = "app"

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"
