[project]
name = "blackpythondevs-site"
version = "0.1.0"
description = "Black Python Devs community website"
requires-python = ">=3.13"
dependencies = ["render-engine[cli]>=2026.3.4a2", "pyyaml"]

[project.optional-dependencies]
dev = [
  "pre-commit",
  "typer",
  "rich",
  "python-frontmatter",
  "ephemeral_port_reserve",
  "pytest-playwright",
  "pytest-xprocess",
  "axe-core-python==0.1.0",
  "axe-playwright-python==0.1.7",
]

[tool.render-engine.cli]
module = "app"
site = "app"

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"
