name: Add Conference
description: Add Conference dates, location, speaking and other information that you would like shared
title: "[CONFERENCE] <CONFERENCE NAME> YYYY"
labels: ["conference", "CFP"]
body:
  - type: input
    id: conference_name
    attributes:
      label: Conference Name
      description: The name of the conference.
      placeholder: <CONFERENCE NAME>
    validations:
      required: true
  - type: input
    attributes:
      label: URL
      description: The full URL of the conference (make sure to include `https://`).
      placeholder: https://example.com
    validations:
      required: true
  - type: input
    id: conference_start_date
    attributes:
      label: Conference Start Date
      description: The start date of the conference. Use `YEAR-MONTH-DAY`
      placeholder: "2024-12-31"
  - type: input
    id: conference_end_date
    attributes:
      label: Conference End Date
      description: The end date of the conference. The website will no longer show the conference after this date. Use `YEAR-MONTH-DAY` format.
      placeholder: "2024-12-31"
  - type: dropdown
    id: conference_type
    attributes:
      label: Conference Type
      description: Is the conference in-person online or both?
      options: ["both", "in-person", "online"]
    validations:
      required: true
  - type: input
    id: conference_location
    attributes:
      label: Conference Location
      description: The location of the conference. Leave blank if online only
      placeholder: "CITY, <REGION>, COUNTRY"
    validations:
      required: false
  - type: input
    id: cfp_link
    attributes:
      label: CFP Link
      description: Provide the URL for the Call for Proposals (CFP) (make sure to include `https://`).
      placeholder: "https://example.com/cfp"
    validations:
      required: false
  - type: input
    id: cfp_deadline
    attributes:
      label: CFP Deadline
      description: Enter the deadline for submitting CFPs (YYYY-MM-DD).
      placeholder: "YYYY-MM-DD"
    validations:
      required: false
  - type: textarea
    id: conference_description
    attributes:
      label: Summary
      description: Summary of the news you're sharing about this conference.
      placeholder: |
        DjangoCon US has been announced alongside it's [website](url).
         The conference is 16-20 October, is a five-day international
         conference for the community by the community about the Django
         web framework, held each year in North America.
    validations:
      required: false
  - type: textarea
    id: conference_speaking
    attributes:
      label: Speaking
      description: Person - Talk or Role
      placeholder: |
        * Dawn Wages - Supercharge your Python and Django Development Environment with VS Code and Dev Containers
        * Kojo Idrissa - Orientation/Welcome & Lightning Talks Host
        * Jay Miller - Panel Discussion: Who put me in charge? Moving beyond day-to-day coding in Django
    validations:
      required: false
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this form, you agree to follow our [Code of Conduct](https://github.com/BlackPythonDevs/.github/blob/main/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
