name: pre-commit
on:
  push:
    branches: ["gh-pages"]
  pull_request:
    branches: ["gh-pages"]

permissions:
  contents: read

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: astral-sh/setup-uv@a9b33f02405f50e505f17ab8530e42a23200a5d1
        with:
          python-version: "3.13"
      - uses: pre-commit/action@2c7b3805fd2a0fd8c1884dcaebf91fc102a13ecd # v3.0.1
