name: pre-commit
on:
  push:
    branches: ["gh-pages"]
  pull_request:
    branches: ["gh-pages"]

permissions:
  contents: read

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
        with:
          persist-credentials: false
      - uses: astral-sh/setup-uv@a9b33f02405f50e505f17ab8530e42a23200a5d1
        with:
          python-version: "3.13"
      - uses: pre-commit/action@646c83fcd040023954eafda54b4db0192ce70507 # v3.0.0
