name: pre-commit
on:
  push:
    branches: ["gh-pages"]
  pull_request:
    branches: ["gh-pages"]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@a9b33f02405f50e505f17ab8530e42a23200a5d1
        with:
          python-version: "3.13"
      - uses: pre-commit/action@v3.0.0
