name: Site Tests

on:
  push:
    branches:
      - gh-pages
  pull_request:
    branches:
      - gh-pages
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Install UV
        uses: astral-sh/setup-uv@38f3f104447c67c051c4a08e39b64a148898af3a # v4
        with:
          version: "latest"
      - name: Set up Python
        run: uv python install 3.14
      - name: Install dependencies
        run: uv sync --dev --prerelease allow
      - name: Run Tests
        run: uv run pytest -v
